version: '3.6'

services:
  alpine-python-flask-hl:
    build: .
    image: hackinglab/alpine-python-flask-hl:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    ports:
      - 80:80


